adding simulating error in yaml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,3 +7,6 @@ jobs:
       - uses: actions/checkout@v3
       - name: Run a sample github action
         run: echo "this workflow run successfully for the particular action"
+
+      - name: simulating error
+        run: echo"error taking place"; exit 1
